#!/bin/zsh

puterr(){
  echo $1 >&2
  error=1
}

pushd coq

  export GREP_COLORS='ms=101:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'
  vfiles=(CL.v
          deBruijn/Untyped.v deBruijn/STLC.v deBruijn/F.v
          LN/Untyped.v Origin/Untyped.v
          lib/Relations_ext.v lib/seq_ext_base.v lib/seq_ext.v
          lib/ssrnat_ext.v)
  COQLIB="-R . LCAC $COQLIB"
  error=

  for f in $vfiles; do
    tail -c 1 $f | grep -q . && puterr "$f: no newline at end of file"
    tail -n 1 $f | grep -qv . && puterr "$f: trailing empty line"
    grep --color=auto -H -n " * $" $f && error=1
  done

  [[ -n $error ]] && exit 1

  (echo $COQLIB; echo $vfiles) > _CoqProject

  make -j ${JOBS:-4} VFILES="$vfiles" COQLIBS="$COQLIB"

popd
