#!/bin/zsh

export GREP_COLORS='ms=101:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'
vfiles=(coq/CL.v
        coq/LC/Debruijn/Untyped.v coq/LC/Debruijn/STLC.v coq/LC/Debruijn/F.v
        coq/LC/LN/Untyped.v coq/LC/Origin/Untyped.v
        coq/lib/Relations_ext.v coq/lib/seq_ext.v coq/lib/ssrnat_ext.v)
error=

puterr(){
  echo $1 >&2
  error=1
}

for f in $vfiles; do
  tail -c 1 $f | grep -q . && puterr "$f: no newline at end of file"
  tail -n 1 $f | grep -qv . && puterr "$f: trailing empty line"
  grep --color=auto -H -n " * $" $f && error=1
done

[[ -n $error ]] && exit 1

make -j ${JOBS:-4} VFILES="$vfiles" COQLIBS="-R coq LCAC $COQLIB"
